[book]
authors = ["Jose Felipe Marcial Rojas", "Miguel Angel Hernandez Moreno"]
language = "en"
multilingual = false
src = "src"
title = "Fox MPI in python"

[output.html]
mathjax-support = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
